project_id = "lms-estimulo"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000/**",
  "http://127.0.0.1:3000/**"
]

[auth.email.template.confirmation]
subject = "Confirme seu e-mail para acessar a Estímulo"
content_path = "./supabase/templates/confirmation.html"
