import { randomUUID } from "node:crypto";
import { Gift, ImageIcon, PackageCheck, WalletCards } from "lucide-react";
import { saveExtensionAction } from "@/app/admin/extension-actions";
import { FileUploadPreview } from "@/components/file-upload-preview";
import { AppShell } from "@/components/app-shell";
import { PendingSubmitButton } from "@/components/pending-submit-button";
import { StatusPanel } from "@/components/status-panel";
import { Card } from "@/components/ui/card";
import { Input, Label, Select, Textarea } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/page-header";
import { StatusPill } from "@/components/ui/status-pill";
import { requireAdminExtensionsWorkspace } from "@/lib/extensions/admin-context";
import type { JsonRecord } from "@/lib/extensions/runtime";
import { REWARD_IMAGE_MAX_BYTES } from "@/lib/storage/reward-images";
import { saveRewardWithImageAction } from "./reward-actions";

export const dynamic = "force-dynamic";

function stringValue(value: unknown) { return typeof value === "string" ? value : ""; }
function numberValue(value: unknown, fallback = 0) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : fallback; }
function record(value: unknown): JsonRecord { return value && typeof value === "object" && !Array.isArray(value) ? value as JsonRecord : {}; }
function fieldKeys(value: unknown) { return new Set(Array.isArray(value) ? value.map(record).map((item) => stringValue(item.key)).filter(Boolean) : []); }
const statusLabels: Record<string, string> = { pending: "Pendente", approved: "Aprovada", preparing: "Em preparação", sent: "Enviada", available: "Disponibilizada", delivered: "Entregue", cancelled: "Cancelada" };
const typeLabels: Record<string, string> = { digital: "Digital", physical: "Física", experience: "Experiência", service: "Serviço" };

export default async function AdminRewardsPage({ searchParams }: { searchParams: Promise<{ erro?: string; sucesso?: string }> }) {
  const query = await searchParams;
  const { auth, workspace } = await requireAdminExtensionsWorkspace();
  const settings = workspace.reward_settings ?? {};

  return <AppShell area="admin" email={auth.email}><div className="grid gap-5">
    <PageHeader eyebrow="Engajamento" title="Recompensas" description="Crie benefícios com imagem, custo e regras de resgate e acompanhe cada pedido em um único lugar." />
    {query.sucesso ? <StatusPanel title="Alteração salva" tone="success">O sistema de recompensas foi atualizado.</StatusPanel> : null}
    {query.erro ? <StatusPanel title="Não foi possível salvar" tone="warning">Revise os campos e tente novamente. Código: {query.erro}</StatusPanel> : null}

    <details className="rounded-2xl border border-border bg-white shadow-sm"><summary className="cursor-pointer p-4 font-bold text-secondary"><span className="inline-flex items-center gap-2"><WalletCards size={18} className="text-primary" />Conversão de pontos</span></summary><form action={saveExtensionAction} className="grid gap-3 border-t border-border p-4 sm:grid-cols-[1fr_auto_1fr_auto] sm:items-end"><input type="hidden" name="resource_type" value="reward_settings" /><input type="hidden" name="return_to" value="/admin/recompensas" /><Label>Pontos de engajamento<Input name="source_points_per_unit" type="number" min="1" defaultValue={String(numberValue(settings.source_points_per_unit, 1))} required /></Label><span className="pb-2 text-sm font-bold text-muted">viram</span><Label>Pontos de recompensa<Input name="reward_points_per_unit" type="number" min="1" defaultValue={String(numberValue(settings.reward_points_per_unit, 1))} required /></Label><PendingSubmitButton pendingLabel="Salvando…">Salvar</PendingSubmitButton></form></details>

    <Card className="grid gap-4"><div className="flex items-start gap-3"><Gift className="mt-0.5 text-primary" /><div><h2 className="text-lg font-black text-secondary">Criar recompensa</h2><p className="text-sm text-muted">Cadastre também uma imagem para tornar o benefício reconhecível no catálogo do participante.</p></div></div><RewardForm /></Card>

    <section className="grid gap-3"><div><p className="brand-kicker">Catálogo</p><h2 className="display-font mt-1 text-2xl text-secondary">Recompensas criadas</h2></div>{workspace.rewards.length === 0 ? <Card><p className="text-sm text-muted">Nenhuma recompensa criada.</p></Card> : <div className="grid gap-3 lg:grid-cols-2">{workspace.rewards.map((reward) => { const rewardId = stringValue(reward.id); const hasImage = Boolean(stringValue(reward.image_file_object_id)); return <Card key={rewardId} className="grid gap-3 overflow-hidden p-0 after:!hidden">{hasImage ? <img src={`/api/rewards/${rewardId}/image`} alt={`Imagem de ${stringValue(reward.name)}`} className="aspect-[16/7] w-full bg-surface-muted object-cover" /> : <div className="grid aspect-[16/5] place-items-center bg-surface-muted text-muted"><ImageIcon size={30} /><span className="sr-only">Sem imagem cadastrada</span></div>}<div className="grid gap-3 p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black text-ink">{stringValue(reward.name)}</h3><p className="text-sm text-muted">{numberValue(reward.cost_points)} ponto(s) · {typeLabels[stringValue(reward.reward_type)] ?? "Recompensa"}</p></div><StatusPill tone={stringValue(reward.status) === "published" ? "success" : "neutral"}>{stringValue(reward.status) === "published" ? "Disponível" : stringValue(reward.status) === "inactive" ? "Desativada" : "Em preparação"}</StatusPill></div><p className="line-clamp-3 text-sm text-muted">{stringValue(reward.description)}</p><p className="text-xs text-muted">Estoque: {reward.stock_quantity === null ? "sem limite" : numberValue(reward.stock_quantity)} · {numberValue(reward.redemption_count)} resgate(s)</p><details className="rounded-xl border border-border"><summary className="cursor-pointer p-3 text-sm font-bold text-secondary">Editar recompensa</summary><div className="border-t border-border p-4"><RewardForm reward={reward} /></div></details></div></Card>; })}</div>}</section>

    <Card className="grid gap-4"><div className="flex items-start gap-3"><PackageCheck className="mt-0.5 text-primary" /><div><h2 className="text-lg font-black text-secondary">Pedidos de resgate</h2><p className="text-sm text-muted">Atualize o andamento e informe ao participante como receberá a recompensa.</p></div></div>{workspace.redemptions.map((redemption) => { const details = record(redemption.fulfillment_details); return <details key={stringValue(redemption.id)} className="rounded-xl border border-border"><summary className="cursor-pointer p-3"><span className="flex flex-wrap items-center justify-between gap-3"><span><strong className="block text-ink">{stringValue(redemption.preferred_name) || stringValue(redemption.legal_name)}</strong><small className="text-muted">{stringValue(redemption.reward_name)} · {numberValue(redemption.points_spent)} ponto(s)</small></span><StatusPill tone={stringValue(redemption.status) === "cancelled" ? "warning" : stringValue(redemption.status) === "delivered" ? "success" : "info"}>{statusLabels[stringValue(redemption.status)] ?? "Em andamento"}</StatusPill></span></summary><form action={saveExtensionAction} className="grid gap-3 border-t border-border p-4 sm:grid-cols-2"><input type="hidden" name="resource_type" value="redemption_status" /><input type="hidden" name="return_to" value="/admin/recompensas" /><input type="hidden" name="id" value={stringValue(redemption.id)} /><Label>Novo andamento<Select name="status" defaultValue={stringValue(redemption.status)}>{Object.entries(statusLabels).map(([status,label]) => <option key={status} value={status}>{label}</option>)}</Select></Label><Label>Motivo do cancelamento<Input name="cancellation_reason" placeholder="Preencha somente ao cancelar" /></Label><Label>Código ou voucher<Input name="delivery_code" defaultValue={stringValue(details.code)} placeholder="Ex.: ABC123" /></Label><Label>Link para acesso<Input name="delivery_link" type="url" defaultValue={stringValue(details.link)} placeholder="https://..." /></Label><Label>Código de rastreio<Input name="delivery_tracking" defaultValue={stringValue(details.tracking)} /></Label><Label className="sm:col-span-2">Orientações para o participante<Textarea name="delivery_notes" rows={3} defaultValue={stringValue(details.instructions)} placeholder="Explique como receber, acessar ou agendar a recompensa." /></Label><PendingSubmitButton pendingLabel="Atualizando…" size="sm">Salvar andamento</PendingSubmitButton></form></details>; })}{workspace.redemptions.length === 0 ? <p className="text-sm text-muted">Nenhum resgate solicitado.</p> : null}</Card>
  </div></AppShell>;
}

function RewardForm({ reward = {} }: { reward?: JsonRecord }) {
  const configuration = record(reward.fulfillment_configuration);
  const keys = fieldKeys(configuration.fields);
  const rewardId = stringValue(reward.id);
  const existingImage = Boolean(stringValue(reward.image_file_object_id));
  return <form action={saveRewardWithImageAction} className="grid gap-3 sm:grid-cols-2">
    <input type="hidden" name="id" value={rewardId} /><input type="hidden" name="code" value={stringValue(reward.code) || `recompensa_${randomUUID().slice(0,8)}`} /><input type="hidden" name="image_file_object_id" value={stringValue(reward.image_file_object_id)} />
    <Label>Nome<Input name="name" defaultValue={stringValue(reward.name)} placeholder="Ex.: Mentoria individual" required /></Label>
    <Label>Tipo<Select name="reward_type" defaultValue={stringValue(reward.reward_type) || "digital"}><option value="digital">Digital</option><option value="physical">Física</option><option value="experience">Experiência</option><option value="service">Serviço</option></Select></Label>
    <Label>Custo em pontos<Input name="cost_points" type="number" min="1" defaultValue={String(numberValue(reward.cost_points, 1))} required /></Label>
    <Label>Quantidade disponível<Input name="stock_quantity" type="number" min="0" defaultValue={reward.stock_quantity === null ? "" : String(numberValue(reward.stock_quantity))} placeholder="Vazio = sem limite" /></Label>
    <Label className="sm:col-span-2">Descrição<Textarea name="description" rows={3} defaultValue={stringValue(reward.description)} required /></Label>
    <FileUploadPreview className="sm:col-span-2" name="reward_image" accept=".png,.jpg,.jpeg,.webp" label="Imagem da recompensa" maxSizeBytes={REWARD_IMAGE_MAX_BYTES} recommendedDimensions="1200 × 675 px" recommendedAspectRatio="16:9" minWidth={600} minHeight={338} existingPreviewUrl={existingImage && rewardId ? `/api/rewards/${rewardId}/image` : null} existingPreviewAlt={`Imagem atual de ${stringValue(reward.name) || "recompensa"}`} help="PNG, JPG ou WEBP. Uma imagem horizontal funciona melhor nos cards da plataforma." />
    <Label className="sm:col-span-2">Regras para resgate<Textarea name="regulation" rows={4} defaultValue={stringValue(reward.regulation)} required /></Label>
    <Label>Disponibilidade<Select name="status" defaultValue={stringValue(reward.status) || "draft"}><option value="draft">Preparar sem mostrar</option><option value="published">Mostrar aos participantes</option><option value="inactive">Retirar do catálogo</option></Select></Label>
    <details className="rounded-xl border border-border sm:col-span-2"><summary className="cursor-pointer p-3 text-sm font-bold text-secondary">Prazo e forma de entrega</summary><div className="grid gap-3 border-t border-border p-3 sm:grid-cols-2"><Label>Limite por pessoa<Input name="max_per_user" type="number" min="1" defaultValue={reward.max_per_user === null ? "" : String(numberValue(reward.max_per_user))} placeholder="Vazio = sem limite" /></Label><Label>Disponível a partir de<Input name="starts_at" type="datetime-local" defaultValue={stringValue(reward.starts_at).slice(0,16)} /></Label><Label>Disponível até<Input name="ends_at" type="datetime-local" defaultValue={stringValue(reward.ends_at).slice(0,16)} /></Label><fieldset className="grid gap-2 rounded-xl bg-surface-muted p-3 sm:col-span-2"><legend className="px-1 text-sm font-bold text-secondary">Dados que o participante deverá informar</legend><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="request_address" defaultChecked={keys.has("address")} className="accent-primary" />Endereço de entrega</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="request_email" defaultChecked={keys.has("email")} className="accent-primary" />E-mail</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="request_phone" defaultChecked={keys.has("phone")} className="accent-primary" />Telefone</label></fieldset><Label className="sm:col-span-2">Instruções de entrega<Textarea name="delivery_instructions" rows={3} defaultValue={stringValue(configuration.instructions)} placeholder="Explique como a equipe entregará ou disponibilizará a recompensa." /></Label></div></details>
    <PendingSubmitButton pendingLabel="Salvando…" className="w-fit sm:col-span-2">Salvar recompensa</PendingSubmitButton>
  </form>;
}
