\set ON_ERROR_STOP on

-- Regression for the 2026-08-19 production incident: changing only an
-- assessment passing score must not replace question identities that are
-- already referenced by historical assessment responses.
do $$
declare
  v_save_definition text;
  v_helper_definition text;
  v_response_fk_delete_action "char";
begin
  if to_regprocedure('app_private.e14_assessment_questions_match_payload(uuid,jsonb)') is null then
    raise exception 'ASSESSMENT_QUESTION_MATCH_HELPER_MISSING';
  end if;

  if to_regprocedure('public.save_admin_lesson(uuid,uuid,jsonb,text)') is null then
    raise exception 'SAVE_ADMIN_LESSON_RPC_MISSING';
  end if;

  v_save_definition := pg_get_functiondef(
    'public.save_admin_lesson(uuid,uuid,jsonb,text)'::regprocedure
  );
  v_helper_definition := pg_get_functiondef(
    'app_private.e14_assessment_questions_match_payload(uuid,jsonb)'::regprocedure
  );

  if position(
    'if not app_private.e14_assessment_questions_match_payload(v_activity_version_id,p_payload#>''{assessment,questions}'')'
    in lower(v_save_definition)
  ) = 0 then
    raise exception 'SAVE_ADMIN_LESSON_RECREATES_UNCHANGED_ASSESSMENT_QUESTIONS';
  end if;

  if position(
    'on conflict(activity_version_id) do update set passing_score=excluded.passing_score,max_attempts=excluded.max_attempts'
    in lower(v_save_definition)
  ) = 0 then
    raise exception 'SAVE_ADMIN_LESSON_SCORE_PATCH_CONTRACT_MISSING';
  end if;

  if position('assessment.answer_options' in lower(v_helper_definition)) = 0
     or position('assessment.questions' in lower(v_helper_definition)) = 0 then
    raise exception 'ASSESSMENT_QUESTION_MATCH_HELPER_DOES_NOT_COMPARE_CURRENT_QUESTION_SET';
  end if;

  -- Question and option codes are generated by the admin form on submit and
  -- are not editable content. Comparing persisted codes here would turn a
  -- passing-score-only edit into a false full-question replacement.
  if position('q.code' in lower(v_helper_definition)) > 0
     or position('ao.code' in lower(v_helper_definition)) > 0 then
    raise exception 'ASSESSMENT_QUESTION_MATCH_HELPER_MUST_IGNORE_GENERATED_CODES';
  end if;

  if has_function_privilege(
       'anon',
       'app_private.e14_assessment_questions_match_payload(uuid,jsonb)',
       'EXECUTE'
     )
     or has_function_privilege(
       'authenticated',
       'app_private.e14_assessment_questions_match_payload(uuid,jsonb)',
       'EXECUTE'
     ) then
    raise exception 'ASSESSMENT_QUESTION_MATCH_HELPER_EXPOSED_TO_CLIENT_ROLES';
  end if;

  if not has_function_privilege(
    'service_role',
    'app_private.e14_assessment_questions_match_payload(uuid,jsonb)',
    'EXECUTE'
  ) then
    raise exception 'ASSESSMENT_QUESTION_MATCH_HELPER_NOT_AVAILABLE_TO_SERVICE_ROLE';
  end if;

  select c.confdeltype
  into v_response_fk_delete_action
  from pg_constraint c
  where c.conname = 'fk_assessment_responses_question_id_assessment_questions'
    and c.conrelid = 'assessment.responses'::regclass;

  if v_response_fk_delete_action is null then
    raise exception 'ASSESSMENT_RESPONSE_QUESTION_FK_MISSING';
  end if;

  if v_response_fk_delete_action = 'c' then
    raise exception 'ASSESSMENT_RESPONSE_HISTORY_MUST_NOT_BE_CASCADE_DELETED';
  end if;
end $$;
