import { ArrowRightLeft, CheckCircle2, Crown, Gift, History, LockKeyhole, Sparkles, Trophy, WalletCards } from "lucide-react";
import { performExtensionAction } from "@/app/empreendedor/extension-actions";
import { PendingSubmitButton } from "@/components/pending-submit-button";
import { Card } from "@/components/ui/card";
import { Input, Label } from "@/components/ui/input";
import { StatusPill } from "@/components/ui/status-pill";
import type { JsonRecord } from "@/lib/extensions/runtime";

function text(value: unknown) { return typeof value === "string" ? value : ""; }
function number(value: unknown) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; }
const statusLabels: Record<string,string> = { pending:"Pedido recebido", approved:"Aprovada", preparing:"Em preparação", sent:"Enviada", available:"Disponível", delivered:"Concluída", cancelled:"Cancelada" };
const typeLabels: Record<string,string> = { digital:"Digital", physical:"Produto", experience:"Experiência", service:"Serviço" };

export function RewardsExperience({ rewards }: { rewards: { settings: JsonRecord; reward_balance: number; convertible_engagement_points: number; catalog: JsonRecord[]; redemptions: JsonRecord[] } }) {
  const rateSource = number(rewards.settings.source_points_per_unit) || 1;
  const rateReward = number(rewards.settings.reward_points_per_unit) || 1;
  const nextReward = rewards.catalog.slice().sort((a,b) => number(a.cost_points)-number(b.cost_points)).find((reward) => number(reward.cost_points) > rewards.reward_balance);
  const nextCost = nextReward ? number(nextReward.cost_points) : 0;
  const progress = nextCost > 0 ? Math.min(100, Math.round((rewards.reward_balance / nextCost) * 100)) : 100;

  return <div className="grid gap-8">
    <section className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-primary via-primary-active to-secondary p-6 text-white shadow-xl sm:p-8">
      <Sparkles className="absolute right-6 top-5 text-white/25" size={72} aria-hidden="true" />
      <div className="relative grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex items-center gap-2 text-sm font-black uppercase tracking-[.14em] text-white/75"><Crown size={18} /> Central de recompensas</div><h1 className="display-font mt-3 text-4xl sm:text-5xl">Transforme seu progresso em conquistas</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/80 sm:text-base">Use os pontos conquistados na plataforma para desbloquear benefícios, experiências e presentes.</p></div><div className="rounded-2xl border border-white/20 bg-white/10 p-5 text-center backdrop-blur"><p className="text-xs font-bold uppercase tracking-wide text-white/70">Seu saldo</p><p className="display-font mt-1 text-5xl">{rewards.reward_balance}</p><p className="text-sm text-white/75">pontos de recompensa</p></div></div>
      {nextReward ? <div className="relative mt-6 rounded-2xl bg-black/15 p-4"><div className="flex flex-wrap items-center justify-between gap-2 text-sm"><span>Próximo objetivo: <strong>{text(nextReward.name)}</strong></span><span>{Math.max(0, nextCost-rewards.reward_balance)} pontos restantes</span></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-white/20"><div className="h-full rounded-full bg-white" style={{ width: `${progress}%` }} /></div></div> : null}
    </section>

    <section className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]">
      <Card className="brand-accent-card after:!hidden"><div className="flex items-start gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-primary-soft text-primary"><WalletCards size={24} /></span><div><p className="text-sm font-semibold text-muted">Pontos prontos para usar</p><p className="display-font mt-1 text-4xl text-secondary">{rewards.reward_balance}</p></div></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-surface-muted p-3"><p className="text-muted">Pontos de engajamento</p><strong className="mt-1 block text-xl text-ink">{rewards.convertible_engagement_points}</strong></div><div className="rounded-xl bg-surface-muted p-3"><p className="text-muted">Conversão</p><strong className="mt-1 block text-xl text-ink">{rateSource} por {rateReward}</strong></div></div></Card>
      <Card><div className="flex items-center gap-2"><ArrowRightLeft className="text-primary" /><h2 className="font-black text-secondary">Converter pontos</h2></div><p className="mt-1 text-sm text-muted">Escolha quantos pontos de engajamento quer transformar. A conversão não pode ser desfeita.</p><form action={performExtensionAction} className="mt-5 grid gap-3"><input type="hidden" name="action_type" value="reward_convert" /><input type="hidden" name="return_to" value="/empreendedor/recompensas" /><Label>Quantidade<Input name="source_points" type="number" min="1" max={rewards.convertible_engagement_points} required placeholder="Digite a quantidade" /></Label><PendingSubmitButton pendingLabel="Convertendo…" disabled={rewards.convertible_engagement_points < 1}>Converter agora</PendingSubmitButton></form></Card>
    </section>

    <section className="grid gap-4"><div className="flex items-end justify-between gap-4"><div><p className="brand-kicker">Escolha sua próxima conquista</p><h2 className="display-font mt-1 text-3xl text-secondary">Recompensas disponíveis</h2></div><Trophy className="hidden text-warning sm:block" size={38} /></div>{rewards.catalog.length === 0 ? <Card><p className="text-sm text-muted">Novas recompensas aparecerão aqui em breve.</p></Card> : <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{rewards.catalog.map((reward) => <RewardCard key={text(reward.id)} reward={reward} balance={rewards.reward_balance} />)}</div>}</section>

    <Card><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-primary-soft text-primary"><History size={20} /></span><div><h2 className="font-black text-secondary">Minha jornada de resgates</h2><p className="text-sm text-muted">Acompanhe cada etapa até a recompensa chegar.</p></div></div><div className="mt-5 grid gap-3">{rewards.redemptions.map((redemption) => <article key={text(redemption.id)} className="flex gap-3 rounded-xl border border-border p-4"><span className={`mt-0.5 grid size-9 shrink-0 place-items-center rounded-full ${text(redemption.status)==="delivered" ? "bg-success/15 text-success" : "bg-primary-soft text-primary"}`}>{text(redemption.status)==="delivered" ? <CheckCircle2 size={18} /> : <Gift size={17} />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold text-ink">{text(redemption.reward_name)}</h3><p className="text-xs text-muted">{number(redemption.points_spent)} pontos utilizados</p></div><StatusPill tone={text(redemption.status) === "cancelled" ? "warning" : text(redemption.status) === "delivered" ? "success" : "info"}>{statusLabels[text(redemption.status)] ?? "Em andamento"}</StatusPill></div>{text(redemption.cancellation_reason) ? <p className="mt-3 text-sm text-warning">{text(redemption.cancellation_reason)}</p> : null}</div></article>)}{rewards.redemptions.length === 0 ? <p className="text-sm text-muted">Seu primeiro resgate aparecerá aqui.</p> : null}</div></Card>
  </div>;
}

function RewardCard({ reward, balance }: { reward: JsonRecord; balance: number }) {
  const cost = number(reward.cost_points);
  const unlocked = balance >= cost;
  const missing = Math.max(0, cost-balance);
  const progress = cost > 0 ? Math.min(100, Math.round((balance/cost)*100)) : 100;
  return <Card className={`flex flex-col overflow-hidden transition hover:-translate-y-1 hover:shadow-xl ${unlocked ? "ring-1 ring-primary/15" : ""}`}><div className="flex items-start justify-between gap-3"><span className={`grid size-14 shrink-0 place-items-center rounded-2xl ${unlocked ? "bg-primary text-white shadow-lg" : "bg-surface-muted text-muted"}`}>{unlocked ? <Gift size={26} /> : <LockKeyhole size={24} />}</span><span className="rounded-full bg-surface-muted px-3 py-1 text-[10px] font-black uppercase tracking-wide text-muted">{typeLabels[text(reward.reward_type)] ?? "Recompensa"}</span></div><h3 className="mt-4 text-xl font-black text-ink">{text(reward.name)}</h3><p className="mt-2 flex-1 text-sm leading-6 text-muted">{text(reward.description)}</p><div className="mt-5 flex items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-muted">Custo</p><p className="display-font text-3xl text-secondary">{cost}</p></div><span className={`text-xs font-bold ${unlocked ? "text-success" : "text-muted"}`}>{unlocked ? "Pronta para resgatar" : `Faltam ${missing}`}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-surface-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${progress}%` }} /></div><details className="mt-4 rounded-xl border border-border"><summary className="cursor-pointer p-3 text-sm font-semibold text-secondary">Ver detalhes</summary><div className="border-t border-border p-3 text-sm whitespace-pre-wrap text-muted">{text(reward.regulation)}</div></details><form action={performExtensionAction} className="mt-4 grid gap-3"><input type="hidden" name="action_type" value="reward_redeem" /><input type="hidden" name="return_to" value="/empreendedor/recompensas" /><input type="hidden" name="reward_id" value={text(reward.id)} /><input type="hidden" name="json_fields" value="fulfillment_details" /><input type="hidden" name="fulfillment_details" value="{}" /><PendingSubmitButton pendingLabel="Solicitando…" disabled={!unlocked}>{unlocked ? "Resgatar recompensa" : `Junte mais ${missing} pontos`}</PendingSubmitButton></form></Card>;
}
