import { Bot, ClipboardCheck, FileUp } from "lucide-react";
import { saveExtensionAction } from "@/app/admin/extension-actions";
import { PendingSubmitButton } from "@/components/pending-submit-button";
import { StatusPanel } from "@/components/status-panel";
import { Card } from "@/components/ui/card";
import { Input, Label, Select, Textarea } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/page-header";
import { StatusPill } from "@/components/ui/status-pill";
import { requireAdminExtensionsWorkspace } from "@/lib/extensions/admin-context";
import type { JsonRecord } from "@/lib/extensions/runtime";

export const dynamic = "force-dynamic";

function text(value: unknown) { return typeof value === "string" ? value : ""; }
function number(value: unknown, fallback = 0) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : fallback; }
function pretty(value: unknown, fallback: unknown) { return JSON.stringify(value ?? fallback, null, 2); }
const formats = ["text","external_link","image","pdf","document","spreadsheet","code","zip","audio","video"];

export default async function AdminDeliveriesPage({ searchParams }: { searchParams: Promise<{ erro?: string; sucesso?: string }> }) {
  const query = await searchParams;
  const { workspace } = await requireAdminExtensionsWorkspace();

  return <div className="grid gap-6">
    <PageHeader eyebrow="Avaliação" title="Entregas e correção por IA" description="Habilite entregas em atividades ou conteúdos independentes da biblioteca e configure rubricas de correção." />
    {query.sucesso ? <StatusPanel title="Alteração salva" tone="success">A configuração de entrega foi atualizada.</StatusPanel> : null}
    {query.erro ? <StatusPanel title="Não foi possível salvar" tone="warning">Código: {query.erro}</StatusPanel> : null}

    <Card className="grid gap-5">
      <div className="flex items-start gap-3"><FileUp className="mt-0.5 text-primary" /><div><h2 className="text-lg font-black text-secondary">Nova entrega</h2><p className="text-sm text-muted">O alvo pode ser uma atividade ou uma versão de conteúdo publicada somente na biblioteca.</p></div></div>
      <DeliveryForm libraryItems={workspace.library_items} activities={workspace.activity_versions} />
    </Card>

    <section className="grid gap-4"><div><p className="brand-kicker">Configurações</p><h2 className="display-font mt-1 text-2xl text-secondary">Atividades com entrega</h2></div>{workspace.delivery_configurations.length === 0 ? <Card><p className="text-sm text-muted">Nenhuma entrega configurada.</p></Card> : <div className="grid gap-4 lg:grid-cols-2">{workspace.delivery_configurations.map((configuration) => <Card key={text(configuration.id)} className="grid gap-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black text-ink">{text(configuration.title)}</h3><p className="text-sm text-muted">{text(configuration.target_title)} · {text(configuration.target_type)}</p></div><StatusPill tone={text(configuration.status) === "active" ? "success" : "neutral"}>{text(configuration.status)}</StatusPill></div><p className="text-sm text-muted">{text(configuration.instructions)}</p><div className="grid grid-cols-2 gap-3 text-xs"><span className="rounded-lg bg-surface-muted p-2">Modo: {text(configuration.grading_mode)}</span><span className="rounded-lg bg-surface-muted p-2">{number(configuration.submission_count)} entrega(s)</span></div><details className="rounded-xl border border-border"><summary className="cursor-pointer p-3 text-sm font-bold text-secondary">Editar configuração</summary><div className="border-t border-border p-4"><DeliveryForm configuration={configuration} libraryItems={workspace.library_items} activities={workspace.activity_versions} /></div></details></Card>)}</div>}</section>

    <Card className="overflow-x-auto">
      <div className="flex items-start gap-3"><ClipboardCheck className="mt-0.5 text-primary" /><div><h2 className="text-lg font-black text-secondary">Fila de correção</h2><p className="text-sm text-muted">A correção original da IA é preservada. Alterações humanas exigem motivo e ficam auditadas.</p></div></div>
      <table className="mt-5 w-full min-w-[1050px] text-sm"><thead><tr className="border-b border-border text-left text-muted"><th className="p-2">Participante</th><th className="p-2">Entrega</th><th className="p-2">Status</th><th className="p-2">IA</th><th className="p-2">Revisão final</th></tr></thead><tbody>{workspace.delivery_submissions.map((submission) => { const reviews = Array.isArray(submission.reviews) ? submission.reviews.filter((item): item is JsonRecord => Boolean(item) && typeof item === "object" && !Array.isArray(item)) : []; const aiReview = reviews.find((review) => review.review_type === "ai"); return <tr key={text(submission.id)} className="border-b border-border/70 align-top"><td className="p-2"><strong className="block text-ink">{text(submission.preferred_name) || text(submission.legal_name)}</strong><span className="text-xs text-muted">{text(submission.email_normalized)}</span></td><td className="p-2"><strong className="block text-ink">{text(submission.delivery_title)}</strong><span className="text-xs text-muted">Tentativa {number(submission.attempt_number)}</span></td><td className="p-2"><StatusPill tone={text(submission.status) === "approved" ? "success" : text(submission.status) === "processing" ? "info" : "warning"}>{text(submission.status)}</StatusPill></td><td className="p-2">{aiReview ? <div><strong>{number(aiReview.score)} / 100</strong><p className="mt-1 max-w-xs text-xs text-muted">{text(aiReview.feedback)}</p><span className="text-[11px] text-muted">Confiança: {number(aiReview.confidence).toFixed(2)}</span></div> : <span className="text-muted">Aguardando análise</span>}</td><td className="p-2"><form action={saveExtensionAction} className="grid min-w-72 gap-2"><input type="hidden" name="resource_type" value="delivery_review" /><input type="hidden" name="return_to" value="/admin/entregas" /><input type="hidden" name="json_fields" value="criterion_scores,metadata" /><input type="hidden" name="submission_id" value={text(submission.id)} /><input type="hidden" name="criterion_scores" value="[]" /><input type="hidden" name="metadata" value="{}" /><Input name="score" type="number" min="0" max="100" step="0.01" defaultValue={submission.final_score === null ? "" : String(number(submission.final_score))} placeholder="Nota" /><Textarea name="feedback" rows={3} defaultValue={text(submission.final_feedback)} placeholder="Feedback final" /><Select name="status" defaultValue={text(submission.status) === "approved" ? "approved" : "corrected"}><option value="corrected">Corrigida</option><option value="approved">Aprovada</option><option value="rejected">Reprovada</option><option value="returned">Devolver para ajuste</option></Select><Input name="change_reason" placeholder="Motivo da decisão ou alteração" required /><PendingSubmitButton pendingLabel="Salvando…" size="sm">Salvar revisão</PendingSubmitButton></form></td></tr>; })}</tbody></table>
      {workspace.delivery_submissions.length === 0 ? <p className="mt-4 text-sm text-muted">Nenhuma entrega recebida.</p> : null}
    </Card>

    <StatusPanel title="Segurança da correção" tone="info"><span className="inline-flex items-center gap-2"><Bot size={17} />Documentos, imagens, áudio e vídeo podem ser extraídos ou transcritos. Código e ZIP passam por análise estática; arquivos enviados nunca são executados diretamente.</span></StatusPanel>
  </div>;
}

function DeliveryForm({ configuration = {}, libraryItems, activities }: { configuration?: JsonRecord; libraryItems: JsonRecord[]; activities: JsonRecord[] }) {
  const targetType = text(configuration.target_type) || "library";
  const targetId = targetType === "library" ? text(configuration.library_item_version_id) : text(configuration.activity_version_id);
  const selectedFormats = Array.isArray(configuration.allowed_submission_types) ? configuration.allowed_submission_types.map(String) : ["text"];
  return <form action={saveExtensionAction} className="grid gap-4 sm:grid-cols-2">
    <input type="hidden" name="resource_type" value="delivery_configuration" /><input type="hidden" name="return_to" value="/admin/entregas" /><input type="hidden" name="array_fields" value="allowed_submission_types,required_submission_types" /><input type="hidden" name="json_fields" value="rubric,reference_material,points_configuration" /><input type="hidden" name="boolean_fields" value="allow_late,allow_resubmit" /><input type="hidden" name="id" value={text(configuration.id)} />
    <Label>Tipo de alvo<Select name="target_type" defaultValue={targetType}><option value="library">Conteúdo da biblioteca</option><option value="activity">Atividade de jornada</option></Select></Label>
    <Label>Alvo<Select name="target_id" defaultValue={targetId} required><option value="">Selecione</option><optgroup label="Biblioteca">{libraryItems.map((item) => <option key={text(item.library_item_version_id)} value={text(item.library_item_version_id)}>{text(item.title)}</option>)}</optgroup><optgroup label="Atividades">{activities.map((item) => <option key={text(item.id)} value={text(item.id)}>{text(item.title)}</option>)}</optgroup></Select><span className="text-[11px] font-normal text-muted">Escolha um item compatível com o tipo de alvo.</span></Label>
    <Label className="sm:col-span-2">Título<Input name="title" defaultValue={text(configuration.title)} required /></Label><Label className="sm:col-span-2">Instruções<Textarea name="instructions" rows={5} defaultValue={text(configuration.instructions)} required /></Label>
    <fieldset className="grid gap-2 rounded-xl border border-border p-4 sm:col-span-2"><legend className="px-2 text-sm font-bold text-secondary">Formatos permitidos</legend><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{formats.map((format) => <label key={format} className="flex items-center gap-2 text-sm"><input type="checkbox" name="allowed_submission_types" value={format} defaultChecked={selectedFormats.includes(format)} className="accent-primary" />{format}</label>)}</div></fieldset>
    <Label>Máximo de arquivos<Input name="max_files" type="number" min="0" max="20" defaultValue={String(number(configuration.max_files, 5))} /></Label><Label>Tamanho máximo por arquivo (bytes)<Input name="max_file_size_bytes" type="number" min="1024" max="104857600" defaultValue={String(number(configuration.max_file_size_bytes, 26214400))} /></Label>
    <Label>Tentativas máximas<Input name="max_attempts" type="number" min="1" defaultValue={configuration.max_attempts === null ? "" : String(number(configuration.max_attempts))} placeholder="Vazio = ilimitadas" /></Label><Label>Nota mínima<Input name="passing_score" type="number" min="0" max="100" step="0.01" defaultValue={configuration.passing_score === null ? "" : String(number(configuration.passing_score))} /></Label>
    <Label>Estratégia da nota<Select name="grade_strategy" defaultValue={text(configuration.grade_strategy) || "highest"}><option value="highest">Maior nota</option><option value="latest">Última tentativa</option><option value="average">Média</option></Select></Label><Label>Modo de correção<Select name="grading_mode" defaultValue={text(configuration.grading_mode) || "ai_human_review"}><option value="automatic">IA publica automaticamente quando confiante</option><option value="ai_human_review">IA prepara e humano aprova</option><option value="ai_assistant">IA apenas auxilia</option></Select></Label>
    <Label>Início<Input name="starts_at" type="datetime-local" defaultValue={text(configuration.starts_at).slice(0,16)} /></Label><Label>Prazo<Input name="due_at" type="datetime-local" defaultValue={text(configuration.due_at).slice(0,16)} /></Label><Label>Encerramento<Input name="ends_at" type="datetime-local" defaultValue={text(configuration.ends_at).slice(0,16)} /></Label><Label>Estado<Select name="status" defaultValue={text(configuration.status) || "active"}><option value="draft">Rascunho</option><option value="active">Ativa</option><option value="inactive">Inativa</option></Select></Label>
    <label className="flex items-center gap-2 text-sm"><input type="hidden" name="allow_late" value="false" /><input type="checkbox" name="allow_late" value="true" defaultChecked={configuration.allow_late === true} className="accent-primary" />Aceitar entrega atrasada</label><label className="flex items-center gap-2 text-sm"><input type="hidden" name="allow_resubmit" value="false" /><input type="checkbox" name="allow_resubmit" value="true" defaultChecked={configuration.allow_resubmit !== false} className="accent-primary" />Permitir reenvio</label>
    <Label className="sm:col-span-2">Rubrica em JSON<Textarea name="rubric" rows={9} defaultValue={pretty(configuration.rubric, { criteria: [{ code: "qualidade", name: "Qualidade", weight: 1, description: "Avalie a qualidade da resposta." }] })} /></Label>
    <Label className="sm:col-span-2">Instruções específicas para a IA<Textarea name="ai_instructions" rows={5} defaultValue={text(configuration.ai_instructions)} /></Label>
    <Label className="sm:col-span-2">Materiais de referência em JSON<Textarea name="reference_material" rows={5} defaultValue={pretty(configuration.reference_material, [])} /></Label>
    <Label className="sm:col-span-2">Pontos em JSON<Textarea name="points_configuration" rows={4} defaultValue={pretty(configuration.points_configuration, { on_submit: 0, on_approve: 0, proportional_to_score: false, max_points: 0 })} /></Label>
    <PendingSubmitButton pendingLabel="Salvando entrega…" className="w-fit sm:col-span-2">Salvar configuração</PendingSubmitButton>
  </form>;
}
