import { randomUUID } from "node:crypto";
import { createEnrollmentAction, moderateActivityCommentAction, publishVerticalAction, reviewPracticeSubmissionAction } from "@/app/actions/journey";
import { AppShell } from "@/components/app-shell";
import { ProgressMeter, StatusPanel } from "@/components/status-panel";
import { Button, ButtonLink } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";
import { Select, Textarea } from "@/components/ui/input";
import { StatusPill } from "@/components/ui/status-pill";
import { administrativeOrganization } from "@/lib/auth/administrative-access";
import { getAuthContext } from "@/lib/auth/context";
import { statusLabel } from "@/lib/journey-runtime/navigation";
import { journeyRuntime } from "@/lib/journey-runtime/rpc";
import { practiceRuntime } from "@/lib/practice/runtime";

export const dynamic = "force-dynamic";
const dateFormatter = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Sao_Paulo" });
const practiceStatus: Record<string, string> = { upload_pending: "Aguardando envio", awaiting_review: "Aguardando revisão", available: "Disponível", accepted: "Aceita", rejected: "Revisão solicitada", failed: "Falha no envio" };
function practiceTone(status: string): "success" | "danger" | "warning" | "neutral" { if (status === "accepted") return "success"; if (status === "rejected") return "danger"; if (status === "awaiting_review") return "warning"; return "neutral"; }
function fileSize(value: number | null) { if (value === null) return null; if (value < 1024) return `${value} B`; if (value < 1024*1024) return `${(value/1024).toFixed(1)} KB`; return `${(value/(1024*1024)).toFixed(1)} MB`; }
function readableLabel(key: string) { return key.replaceAll("_"," ").replace(/\b\w/g,(letter) => letter.toUpperCase()).replace(/ Id\b/g,"").replace(/ Uuid\b/g,""); }
function readableValue(value: unknown) { if (value === null || value === undefined || value === "") return "Não informado"; if (typeof value === "boolean") return value ? "Sim" : "Não"; if (typeof value === "number") return new Intl.NumberFormat("pt-BR").format(value); if (typeof value === "string") { const date=Date.parse(value); if (/^\d{4}-\d{2}-\d{2}T/.test(value)&&Number.isFinite(date)) return dateFormatter.format(new Date(date)); if (/^[0-9a-f-]{36}$/i.test(value)) return "Registro interno confirmado"; return value; } if (Array.isArray(value)) return `${value.length} item(ns) registrados`; if (typeof value === "object") return `${Object.keys(value as Record<string,unknown>).length} campo(s) registrados`; return String(value); }

export default async function AdminOperationPage({ searchParams }: { searchParams: Promise<{ area?: string; instance?: string; sucesso?: string; comentario?: string; pratica?: string }> }) {
  const query = await searchParams;
  const auth = await getAuthContext();
  if (auth.status !== "authenticated") return null;
  const organization = administrativeOrganization(auth.identity);
  if (!organization) return <AppShell area="admin" email={auth.email}><StatusPanel title="Área indisponível" tone="warning">Seu usuário não está vinculado à Estímulo.</StatusPanel></AppShell>;
  const area = ["matriculas","praticas","comentarios","instancias"].includes(query.area ?? "") ? query.area! : "matriculas";
  const canManageComments = organization.permissions.includes("engagement.manage");
  const canReviewPractice = organization.permissions.includes("assessment.review");

  const [listing, workspaceResult, commentResult, practiceResult] = await Promise.all([
    area === "instancias" ? journeyRuntime.listOperatorInstances(auth.identity.user_account_id, organization.organization_id) : Promise.resolve({ organization_id: organization.organization_id, instances: [] }),
    area === "matriculas" ? journeyRuntime.getOperatorWorkspace(auth.identity.user_account_id, organization.organization_id).catch(() => null) : Promise.resolve(null),
    area === "comentarios" && canManageComments ? journeyRuntime.listOperatorActivityComments(auth.identity.user_account_id, organization.organization_id, 100).catch(() => null) : Promise.resolve(null),
    area === "praticas" && canReviewPractice ? practiceRuntime.listOperator(auth.identity.user_account_id, organization.organization_id, 100).catch(() => null) : Promise.resolve(null),
  ]);
  const comments = commentResult?.comments ?? [];
  const practices = practiceResult?.submissions ?? [];
  const result = area === "instancias" && query.instance ? await journeyRuntime.getOperatorResult(auth.identity.user_account_id, organization.organization_id, query.instance) : null;

  return <AppShell area="admin" email={auth.email}><div className="grid gap-7">
    <PageHeader eyebrow="Operação" title="Operação da plataforma" description="Escolha uma tarefa. Apenas os dados e comandos relacionados a ela serão carregados." />
    <nav className="grid gap-2 rounded-xl border border-border bg-white p-2 sm:grid-cols-2 lg:grid-cols-4"><ButtonLink href="/admin/operacao?area=matriculas" variant={area === "matriculas" ? "primary" : "ghost"} size="sm">Publicação e matrículas</ButtonLink><ButtonLink href="/admin/operacao?area=praticas" variant={area === "praticas" ? "primary" : "ghost"} size="sm">Revisar entregas</ButtonLink><ButtonLink href="/admin/operacao?area=comentarios" variant={area === "comentarios" ? "primary" : "ghost"} size="sm">Moderar comentários</ButtonLink><ButtonLink href="/admin/operacao?area=instancias" variant={area === "instancias" ? "primary" : "ghost"} size="sm">Acompanhar jornadas</ButtonLink></nav>
    {query.sucesso ? <StatusPanel title="Operação concluída" tone="success">A alteração foi confirmada.</StatusPanel> : null}
    {query.comentario === "moderado" ? <StatusPanel title="Comentário moderado" tone="success">O histórico foi registrado.</StatusPanel> : null}
    {query.pratica === "revisada" ? <StatusPanel title="Prática revisada" tone="success">A decisão e o feedback foram registrados.</StatusPanel> : null}

    {area === "matriculas" ? !workspaceResult ? <StatusPanel title="Operação indisponível" tone="warning">Não foi possível consultar versões e participantes.</StatusPanel> : <div className="grid gap-5 lg:grid-cols-2"><Card><h2 className="text-lg font-semibold text-ink">Publicar versão</h2><p className="mt-1 text-sm text-muted">Use preferencialmente o fluxo guiado de Jornadas. Este comando atende a operação excepcional.</p>{workspaceResult.journey_versions.filter((item) => item.status === "draft").length === 0 ? <p className="mt-4 text-sm text-muted">Nenhum rascunho pronto.</p> : <form action={publishVerticalAction} className="mt-4 grid gap-4"><input type="hidden" name="organization_id" value={organization.organization_id} /><input type="hidden" name="idempotency_key" value={randomUUID()} /><label className="grid gap-1.5 text-sm font-medium text-ink">Versão<Select name="journey_selection" required>{workspaceResult.journey_versions.filter((item) => item.status === "draft").map((item) => <option key={item.journey_version_id} value={`${item.journey_version_id}:${item.content_hash}`}>{item.title} · versão {item.version_number}</option>)}</Select></label><Button type="submit" className="w-fit">Publicar</Button></form>}</Card><Card><h2 className="text-lg font-semibold text-ink">Matricular participante</h2><p className="mt-1 text-sm text-muted">Associe uma pessoa a uma jornada publicada.</p>{workspaceResult.participants.length === 0 || workspaceResult.journey_versions.filter((item) => item.status === "published").length === 0 ? <p className="mt-4 text-sm text-muted">É necessário ter participante e jornada publicada.</p> : <form action={createEnrollmentAction} className="mt-4 grid gap-4"><input type="hidden" name="organization_id" value={organization.organization_id} /><input type="hidden" name="idempotency_key" value={randomUUID()} /><label className="grid gap-1.5 text-sm font-medium text-ink">Participante<Select name="entrepreneur_id" required>{workspaceResult.participants.map((item) => <option key={item.entrepreneur_id} value={item.entrepreneur_id}>{item.display_name} · {item.email}</option>)}</Select></label><label className="grid gap-1.5 text-sm font-medium text-ink">Jornada<Select name="journey_version_id" required>{workspaceResult.journey_versions.filter((item) => item.status === "published").map((item) => <option key={item.journey_version_id} value={item.journey_version_id}>{item.title} · versão {item.version_number}</option>)}</Select></label><Button type="submit" className="w-fit">Matricular</Button></form>}</Card></div> : null}

    {area === "praticas" ? !canReviewPractice ? <StatusPanel title="Revisão restrita" tone="warning">Seu papel não permite revisar entregas.</StatusPanel> : practices.length === 0 ? <EmptyState title="Nenhuma prática aguardando revisão" tone="success">Não há evidências pendentes.</EmptyState> : <section className="grid gap-4" id="praticas">{practices.map((practice) => <Card key={practice.id}><div className="mb-2 flex flex-wrap items-center gap-2"><strong className="text-ink">{practice.participant_name}</strong><StatusPill tone={practiceTone(practice.status)}>{practiceStatus[practice.status] ?? practice.status}</StatusPill><time dateTime={practice.submitted_at} className="ml-auto text-xs text-muted">{dateFormatter.format(new Date(practice.submitted_at))}</time></div><p className="text-sm text-muted">{practice.activity_title} · envio {practice.submission_number}</p><p className="mt-1 text-sm text-ink">{practice.original_filename ?? "Arquivo em preparação"}</p><div className="mt-2 flex flex-wrap gap-x-4 text-xs text-muted"><span>{practice.content_type ?? "Formato em validação"}</span>{fileSize(practice.size_bytes) ? <span>{fileSize(practice.size_bytes)}</span> : null}</div>{practice.can_download ? <ButtonLink href={`/api/practice-submissions/${practice.id}/download`} variant="secondary" size="sm" className="mt-3 w-fit">Baixar evidência</ButtonLink> : null}{practice.status === "awaiting_review" ? <div className="mt-4 grid gap-3 border-t border-border pt-4 sm:grid-cols-2"><form action={reviewPracticeSubmissionAction} className="grid gap-3"><input type="hidden" name="organization_id" value={organization.organization_id} /><input type="hidden" name="submission_id" value={practice.id} /><input type="hidden" name="status" value="accepted" /><input type="hidden" name="idempotency_key" value={randomUUID()} /><label className="grid gap-1.5 text-sm font-medium text-ink">Feedback opcional<Textarea name="feedback" rows={2} maxLength={2000} /></label><Button type="submit" className="w-fit">Aceitar</Button></form><form action={reviewPracticeSubmissionAction} className="grid gap-3"><input type="hidden" name="organization_id" value={organization.organization_id} /><input type="hidden" name="submission_id" value={practice.id} /><input type="hidden" name="status" value="rejected" /><input type="hidden" name="idempotency_key" value={randomUUID()} /><label className="grid gap-1.5 text-sm font-medium text-ink">Motivo do ajuste<Textarea name="feedback" rows={2} required /></label><Button variant="secondary" type="submit" className="w-fit">Solicitar ajuste</Button></form></div> : null}</Card>)}</section> : null}

    {area === "comentarios" ? !canManageComments ? <StatusPanel title="Moderação restrita" tone="warning">Seu papel não permite moderar comentários.</StatusPanel> : comments.length === 0 ? <EmptyState title="Nenhum comentário para moderar" tone="success">A fila está vazia.</EmptyState> : <section className="grid gap-4" id="comentarios">{comments.map((comment) => <Card key={comment.id}><div className="mb-2 flex flex-wrap items-center gap-2"><strong className="text-ink">{comment.author_name}</strong><StatusPill tone={comment.status === "visible" ? "success" : "neutral"}>{comment.status === "visible" ? "Visível" : "Oculto"}</StatusPill><time dateTime={comment.created_at} className="ml-auto text-xs text-muted">{dateFormatter.format(new Date(comment.created_at))}</time></div><p className="text-sm text-muted">{comment.activity_title}</p><p className="mt-1 text-sm text-ink">{comment.body}</p>{comment.status === "visible" ? <form action={moderateActivityCommentAction} className="mt-4 grid gap-3 border-t border-border pt-4"><input type="hidden" name="organization_id" value={organization.organization_id} /><input type="hidden" name="comment_id" value={comment.id} /><input type="hidden" name="status" value="hidden" /><input type="hidden" name="idempotency_key" value={randomUUID()} /><label className="grid gap-1.5 text-sm font-medium text-ink">Justificativa<Textarea name="reason" rows={2} required /></label><Button variant="secondary" type="submit" className="w-fit">Ocultar</Button></form> : <form action={moderateActivityCommentAction} className="mt-4 border-t border-border pt-4"><input type="hidden" name="organization_id" value={organization.organization_id} /><input type="hidden" name="comment_id" value={comment.id} /><input type="hidden" name="status" value="visible" /><input type="hidden" name="reason" value="" /><input type="hidden" name="idempotency_key" value={randomUUID()} /><Button variant="secondary" type="submit">Restaurar</Button></form>}</Card>)}</section> : null}

    {area === "instancias" ? <section className="grid gap-4"><h2 className="text-xl font-semibold text-ink">Jornadas em execução</h2>{listing.instances.length === 0 ? <EmptyState title="Nenhuma instância real" tone="info">Ainda não há jornadas executadas.</EmptyState> : <div className="grid gap-4 sm:grid-cols-2">{listing.instances.map((instance) => <Card key={instance.journey_instance_id}><div className="mb-3 flex flex-wrap items-center gap-2"><StatusPill tone="info">{statusLabel(instance.journey_status)}</StatusPill><span className="text-sm text-muted">{instance.journey_code}</span></div><ProgressMeter value={instance.progress} label="Progresso" /><ButtonLink href={`/admin/operacao?area=instancias&instance=${instance.journey_instance_id}`} variant="secondary" size="sm" className="mt-4 w-fit">Abrir evidências</ButtonLink></Card>)}</div>}{result ? <Card className="mt-2 grid gap-4"><h3 className="text-lg font-semibold text-ink">Evidência selecionada</h3><dl className="grid gap-3 sm:grid-cols-2">{Object.entries(result).map(([key,value]) => <div key={key} className="rounded-lg border border-border p-4"><dt className="text-xs font-semibold uppercase tracking-wide text-muted">{readableLabel(key)}</dt><dd className="mt-1 text-sm text-ink">{readableValue(value)}</dd></div>)}</dl></Card> : null}</section> : null}
  </div></AppShell>;
}