import { randomUUID } from "node:crypto";
import { createEnrollmentAction, moderateActivityCommentAction, publishVerticalAction, reviewPracticeSubmissionAction } from "@/app/actions/journey";
import { AppShell } from "@/components/app-shell";
import { ProgressMeter, StatusPanel } from "@/components/status-panel";
import { Button, ButtonLink } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";
import { Select, Textarea } from "@/components/ui/input";
import { StatusPill } from "@/components/ui/status-pill";
import { administrativeOrganization } from "@/lib/auth/administrative-access";
import { getAuthContext } from "@/lib/auth/context";
import { statusLabel } from "@/lib/journey-runtime/navigation";
import { journeyRuntime } from "@/lib/journey-runtime/rpc";
import { practiceRuntime } from "@/lib/practice/runtime";

export const dynamic = "force-dynamic";
const dateFormatter = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Sao_Paulo" });
const practiceStatus: Record<string, string> = { upload_pending: "Aguardando envio", awaiting_review: "Aguardando revisão", available: "Disponível", accepted: "Aceita", rejected: "Revisão solicitada", failed: "Falha no envio" };
function practiceTone(status: string): "success" | "danger" | "warning" | "neutral" { if (status === "accepted") return "success"; if (status === "rejected") return "danger"; if (status === "awaiting_review") return "warning"; return "neutral"; }
function readableLabel(key: string) { return key.replaceAll("_"," ").replace(/\b\w/g,(letter) => letter.toUpperCase()).replace(/ Id\b/g,""); }
function readableValue(value: unknown) { if (value === null || value === undefined || value === "") return "Não informado"; if (typeof value === "boolean") return value ? "Sim" : "Não"; if (typeof value === "number") return new Intl.NumberFormat("pt-BR").format(value); if (typeof value === "string") return /^[0-9a-f-]{36}$/i.test(value) ? "Registro interno confirmado" : value; if (Array.isArray(value)) return `${value.length} item(ns)`; if (typeof value === "object") return `${Object.keys(value as Record<string,unknown>).length} campo(s)`; return String(value); }

export default async function AdminOperationPage({ searchParams }: { searchParams: Promise<{ area?: string; instance?: string; sucesso?: string; comentario?: string; pratica?: string }> }) {
  const query = await searchParams;
  const auth = await getAuthContext();
  if (auth.status !== "authenticated") return null;
  const organization = administrativeOrganization(auth.identity);
  if (!organization) return <AppShell area="admin" email={auth.email}><StatusPanel title="Área indisponível" tone="warning">Seu usuário não está vinculado à Estímulo.</StatusPanel></AppShell>;
  const area = ["matriculas","praticas","comentarios","instancias"].includes(query.area ?? "") ? query.area! : "matriculas";
  const canManageJourneys = organization.permissions.includes("journey.execution.manage");
  const canManageComments = organization.permissions.includes("engagement.manage");
  const canReviewPractice = organization.permissions.includes("assessment.review");

  const [listing, workspaceResult, commentResult, practiceResult] = await Promise.all([
    area === "instancias" ? journeyRuntime.listOperatorInstances(auth.identity.user_account_id, organization.organization_id) : Promise.resolve({ organization_id: organization.organization_id, instances: [] }),
    area === "matriculas" ? journeyRuntime.getOperatorWorkspace(auth.identity.user_account_id, organization.organization_id).catch(() => null) : Promise.resolve(null),
    area === "comentarios" ? journeyRuntime.listOperatorActivityComments(auth.identity.user_account_id, organization.organization_id, 100).catch(() => null) : Promise.resolve(null),
    area === "praticas" ? practiceRuntime.listOperator(auth.identity.user_account_id, organization.organization_id, 100).catch(() => null) : Promise.resolve(null),
  ]);
  const comments = commentResult?.comments ?? [];
  const practices = practiceResult?.submissions ?? [];
  const result = area === "instancias" && query.instance ? await journeyRuntime.getOperatorResult(auth.identity.user_account_id, organization.organization_id, query.instance) : null;

  return <AppShell area="admin" email={auth.email}><div className="grid gap-7">
    <PageHeader eyebrow="Operação" title="Operação da plataforma" description="Toda a equipe Estímulo pode consultar a operação. Comandos aparecem somente para Administradores gerais." />
    {!canManageJourneys && !canManageComments && !canReviewPractice ? <StatusPanel title="Acesso somente para visualização" tone="info">Você pode consultar matrículas, entregas, comentários e jornadas, mas não pode realizar alterações.</StatusPanel> : null}
    <nav className="grid gap-2 rounded-xl border border-border bg-white p-2 sm:grid-cols-2 lg:grid-cols-4"><ButtonLink href="/admin/operacao?area=matriculas" variant={area === "matriculas" ? "primary" : "ghost"} size="sm">Publicação e matrículas</ButtonLink><ButtonLink href="/admin/operacao?area=praticas" variant={area === "praticas" ? "primary" : "ghost"} size="sm">Entregas</ButtonLink><ButtonLink href="/admin/operacao?area=comentarios" variant={area === "comentarios" ? "primary" : "ghost"} size="sm">Comentários</ButtonLink><ButtonLink href="/admin/operacao?area=instancias" variant={area === "instancias" ? "primary" : "ghost"} size="sm">Jornadas em execução</ButtonLink></nav>

    {area === "matriculas" ? !workspaceResult ? <StatusPanel title="Operação indisponível" tone="warning">Não foi possível consultar versões e participantes.</StatusPanel> : <div className="grid gap-5 lg:grid-cols-2"><Card><h2 className="text-lg font-semibold text-ink">Versões de jornada</h2><div className="mt-4 grid gap-2">{workspaceResult.journey_versions.map((item) => <div key={item.journey_version_id} className="rounded-lg border border-border p-3"><strong>{item.title}</strong><p className="text-sm text-muted">Versão {item.version_number} · {item.status}</p></div>)}</div>{canManageJourneys && workspaceResult.journey_versions.some((item) => item.status === "draft") ? <form action={publishVerticalAction} className="mt-5 grid gap-3 border-t border-border pt-4"><input type="hidden" name="organization_id" value={organization.organization_id} /><input type="hidden" name="idempotency_key" value={randomUUID()} /><Select name="journey_selection" required>{workspaceResult.journey_versions.filter((item) => item.status === "draft").map((item) => <option key={item.journey_version_id} value={`${item.journey_version_id}:${item.content_hash}`}>{item.title} · versão {item.version_number}</option>)}</Select><Button type="submit" className="w-fit">Publicar versão</Button></form> : null}</Card><Card><h2 className="text-lg font-semibold text-ink">Participantes</h2><div className="mt-4 grid gap-2">{workspaceResult.participants.map((item) => <div key={item.entrepreneur_id} className="rounded-lg border border-border p-3"><strong>{item.display_name}</strong><p className="text-sm text-muted">{item.email}</p></div>)}</div>{canManageJourneys && workspaceResult.participants.length && workspaceResult.journey_versions.some((item) => item.status === "published") ? <form action={createEnrollmentAction} className="mt-5 grid gap-3 border-t border-border pt-4"><input type="hidden" name="organization_id" value={organization.organization_id} /><input type="hidden" name="idempotency_key" value={randomUUID()} /><Select name="entrepreneur_id" required>{workspaceResult.participants.map((item) => <option key={item.entrepreneur_id} value={item.entrepreneur_id}>{item.display_name}</option>)}</Select><Select name="journey_version_id" required>{workspaceResult.journey_versions.filter((item) => item.status === "published").map((item) => <option key={item.journey_version_id} value={item.journey_version_id}>{item.title}</option>)}</Select><Button type="submit" className="w-fit">Matricular</Button></form> : null}</Card></div> : null}

    {area === "praticas" ? practices.length === 0 ? <EmptyState title="Nenhuma entrega" tone="info">Não há evidências registradas.</EmptyState> : <section className="grid gap-4" id="praticas">{practices.map((practice) => <Card key={practice.id}><div className="mb-2 flex flex-wrap items-center gap-2"><strong className="text-ink">{practice.participant_name}</strong><StatusPill tone={practiceTone(practice.status)}>{practiceStatus[practice.status] ?? practice.status}</StatusPill><time dateTime={practice.submitted_at} className="ml-auto text-xs text-muted">{dateFormatter.format(new Date(practice.submitted_at))}</time></div><p className="text-sm text-muted">{practice.activity_title} · envio {practice.submission_number}</p>{practice.can_download ? <ButtonLink href={`/api/practice-submissions/${practice.id}/download`} variant="secondary" size="sm" className="mt-3 w-fit">Baixar evidência</ButtonLink> : null}{canReviewPractice && practice.status === "awaiting_review" ? <div className="mt-4 grid gap-3 border-t border-border pt-4 sm:grid-cols-2"><form action={reviewPracticeSubmissionAction} className="grid gap-3"><input type="hidden" name="organization_id" value={organization.organization_id} /><input type="hidden" name="submission_id" value={practice.id} /><input type="hidden" name="status" value="accepted" /><input type="hidden" name="idempotency_key" value={randomUUID()} /><Textarea name="feedback" rows={2} maxLength={2000} /><Button type="submit" className="w-fit">Aceitar</Button></form><form action={reviewPracticeSubmissionAction} className="grid gap-3"><input type="hidden" name="organization_id" value={organization.organization_id} /><input type="hidden" name="submission_id" value={practice.id} /><input type="hidden" name="status" value="rejected" /><input type="hidden" name="idempotency_key" value={randomUUID()} /><Textarea name="feedback" rows={2} required /><Button variant="secondary" type="submit" className="w-fit">Solicitar ajuste</Button></form></div> : null}</Card>)}</section> : null}

    {area === "comentarios" ? comments.length === 0 ? <EmptyState title="Nenhum comentário" tone="info">Não há comentários registrados.</EmptyState> : <section className="grid gap-4" id="comentarios">{comments.map((comment) => <Card key={comment.id}><div className="mb-2 flex flex-wrap items-center gap-2"><strong>{comment.author_name}</strong><StatusPill tone={comment.status === "visible" ? "success" : "neutral"}>{comment.status === "visible" ? "Visível" : "Oculto"}</StatusPill></div><p className="text-sm text-muted">{comment.activity_title}</p><p className="mt-1 text-sm text-ink">{comment.body}</p>{canManageComments ? <form action={moderateActivityCommentAction} className="mt-4 grid gap-3 border-t border-border pt-4"><input type="hidden" name="organization_id" value={organization.organization_id} /><input type="hidden" name="comment_id" value={comment.id} /><input type="hidden" name="status" value={comment.status === "visible" ? "hidden" : "visible"} /><input type="hidden" name="idempotency_key" value={randomUUID()} />{comment.status === "visible" ? <Textarea name="reason" rows={2} required /> : <input type="hidden" name="reason" value="" />}<Button variant="secondary" type="submit" className="w-fit">{comment.status === "visible" ? "Ocultar" : "Restaurar"}</Button></form> : null}</Card>)}</section> : null}

    {area === "instancias" ? <section className="grid gap-4"><h2 className="text-xl font-semibold text-ink">Jornadas em execução</h2>{listing.instances.length === 0 ? <EmptyState title="Nenhuma instância real" tone="info">Ainda não há jornadas executadas.</EmptyState> : <div className="grid gap-4 sm:grid-cols-2">{listing.instances.map((instance) => <Card key={instance.journey_instance_id}><div className="mb-3 flex flex-wrap items-center gap-2"><StatusPill tone="info">{statusLabel(instance.journey_status)}</StatusPill><span className="text-sm text-muted">{instance.journey_code}</span></div><ProgressMeter value={instance.progress} label="Progresso" /><ButtonLink href={`/admin/operacao?area=instancias&instance=${instance.journey_instance_id}`} variant="secondary" size="sm" className="mt-4 w-fit">Abrir evidências</ButtonLink></Card>)}</div>}{result ? <Card className="mt-2 grid gap-4"><h3 className="text-lg font-semibold text-ink">Evidência selecionada</h3><dl className="grid gap-3 sm:grid-cols-2">{Object.entries(result).map(([key,value]) => <div key={key} className="rounded-lg border border-border p-4"><dt className="text-xs font-semibold uppercase tracking-wide text-muted">{readableLabel(key)}</dt><dd className="mt-1 text-sm text-ink">{readableValue(value)}</dd></div>)}</dl></Card> : null}</section> : null}
  </div></AppShell>;
}
