import { ImageUp } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { FileUploadPreview } from "@/components/file-upload-preview";
import { StatusPanel } from "@/components/status-panel";
import { Button, ButtonLink } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input, Label, Select, Textarea } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableScroll, Td, Th } from "@/components/ui/table";
import { getAdminProductWorkspace } from "@/lib/admin/product-management";
import { administrativeOrganization } from "@/lib/auth/administrative-access";
import { getAuthContext } from "@/lib/auth/context";
import { saveGamificationResourceAction } from "./actions";

export const dynamic = "force-dynamic";
function single(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] ?? "" : value ?? ""; }
const frequencyLabels: Record<string, string> = { enrollment_activity: "Uma vez por aula", enrollment_assessment: "Uma vez por avaliação", day: "Limite diário", week: "Limite semanal", unlimited: "Sem limite" };

export default async function AdminGamificationPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = await searchParams;
  const auth = await getAuthContext();
  if (auth.status !== "authenticated") return null;
  const organization = administrativeOrganization(auth.identity);
  if (!organization?.permissions.includes("engagement.manage")) return <AppShell area="admin" email={auth.email}><StatusPanel title="Pontuação restrita" tone="warning">Seu papel não permite configurar pontos e certificados.</StatusPanel></AppShell>;

  const workspace = await getAdminProductWorkspace(auth.identity.user_account_id, organization.organization_id);
  const ruleVersions = workspace.rules.flatMap((item) => item.versions.map((version) => ({ ...version, definitionName: item.name })));
  const journeyVersions = workspace.journeys.filter((item) => item.status !== "retired").flatMap((item) => item.versions.map((version) => ({ ...version, definitionName: item.name })));
  const type = ["pontos", "selos", "certificados"].includes(single(query.tipo)) ? single(query.tipo) : "pontos";
  const templateId = single(query.template);
  const templateName = single(query.templateNome);
  const activePointRules = workspace.point_rules.filter((item) => item.status !== "retired");

  return <AppShell area="admin" email={auth.email}><div className="grid gap-7">
    <PageHeader eyebrow="Engajamento" title="Pontuação e certificados" description="Escolha uma área. As demais configurações permanecem ocultas até você precisar delas." />
    <nav className="grid gap-2 rounded-xl border border-border bg-white p-2 sm:grid-cols-3"><ButtonLink href="/admin/gamificacao?tipo=pontos" variant={type === "pontos" ? "primary" : "ghost"} size="sm">Pontos</ButtonLink><ButtonLink href="/admin/gamificacao?tipo=selos" variant={type === "selos" ? "primary" : "ghost"} size="sm">Selos</ButtonLink><ButtonLink href="/admin/gamificacao?tipo=certificados" variant={type === "certificados" ? "primary" : "ghost"} size="sm">Certificados</ButtonLink></nav>
    {single(query.sucesso) ? <StatusPanel title="Configuração salva" tone="success">A nova versão foi registrada e os participantes verão os valores publicados.</StatusPanel> : null}
    {single(query.erro) ? <StatusPanel title="Não foi possível salvar" tone="warning">Revise os campos obrigatórios.</StatusPanel> : null}

    {type === "pontos" ? <div className="grid gap-5">
      <Card><h2 className="text-lg font-semibold text-ink">Regras publicadas</h2><p className="mt-1 text-sm text-muted">Esta mesma tabela é exibida para o participante na aba Pontuação.</p>{activePointRules.length ? <TableScroll className="mt-4"><Table><thead><tr><Th>Ação</Th><Th>Pontos</Th><Th>Frequência</Th></tr></thead><tbody>{activePointRules.map((item) => { const version = item.versions.find((entry) => String(entry.status) === "published") ?? item.versions[0]; const recurrence = (version?.recurrence_policy ?? {}) as Record<string, unknown>; return <tr key={item.definition_id}><Td><strong>{item.name}</strong></Td><Td>{String(version?.amount ?? "—")}</Td><Td>{frequencyLabels[String(recurrence.scope ?? "")] ?? "Uma única vez"}</Td></tr>; })}</tbody></Table></TableScroll> : <p className="mt-4 text-sm text-muted">Nenhuma regra criada.</p>}</Card>
      <Card><h2 className="text-lg font-semibold text-ink">Criar ou atualizar regra</h2><form action={saveGamificationResourceAction} className="mt-5 grid gap-4 sm:grid-cols-2"><input type="hidden" name="resource_type" value="point_rule" /><Label>Regra existente<Select name="definition_id"><option value="">Criar nova</option>{activePointRules.map((item) => <option value={item.definition_id} key={item.definition_id}>{item.name}</option>)}</Select></Label><Label>Nome da ação<Input name="name" required placeholder="Ex.: Concluir uma aula" /></Label><Label>Pontos por ação<Input name="amount" type="number" min="0" required defaultValue="10" /></Label><Label>Frequência<Select name="frequency" defaultValue="once"><option value="once">Uma única vez</option><option value="per_activity">Uma vez por aula</option><option value="per_assessment">Uma vez por avaliação</option><option value="daily">Limite por dia</option><option value="weekly">Limite por semana</option><option value="unlimited">Sempre</option></Select></Label><Label>Máximo no período<Input name="maximum_awards" type="number" min="1" defaultValue="1" /></Label><Label>Condição necessária<Select name="eligibility_rule_version_id" required><option value="">Selecione</option>{ruleVersions.map((item) => <option value={String(item.id)} key={String(item.id)}>{item.definitionName} · versão {String(item.version_number)}</option>)}</Select></Label><Label>Disponibilidade<Select name="status"><option value="draft">Rascunho</option><option value="published">Publicar agora</option></Select></Label><Button type="submit" className="w-fit sm:col-span-2">Salvar regra</Button></form></Card>
    </div> : null}

    {type === "selos" ? <Card><h2 className="text-lg font-semibold text-ink">Criar ou atualizar selo</h2><form action={saveGamificationResourceAction} className="mt-5 grid gap-4 sm:grid-cols-2"><input type="hidden" name="resource_type" value="badge" /><Label>Selo existente<Select name="definition_id"><option value="">Criar novo</option>{workspace.badges.map((item) => <option value={item.definition_id} key={item.definition_id}>{item.name}</option>)}</Select></Label><Label>Nome interno<Input name="name" required /></Label><Label>Título para o participante<Input name="title" required /></Label><Label className="sm:col-span-2">O que reconhece<Textarea name="description" rows={3} required /></Label><Label>Condição para receber<Select name="criteria_rule_version_id" required><option value="">Selecione</option>{ruleVersions.map((item) => <option value={String(item.id)} key={String(item.id)}>{item.definitionName} · versão {String(item.version_number)}</option>)}</Select></Label><Label>Disponibilidade<Select name="status"><option value="draft">Rascunho</option><option value="published">Publicar agora</option></Select></Label><Button type="submit" className="w-fit sm:col-span-2">Salvar selo</Button></form></Card> : null}

    {type === "certificados" ? <div className="grid gap-5">
      <Card><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary text-white"><ImageUp size={18} /></span><div><h2 className="font-semibold text-ink">Template visual</h2><p className="mt-1 text-sm text-muted">Use uma imagem JPG horizontal. Nome, jornada, data e código serão inseridos automaticamente.</p></div></div>{single(query.templateStatus) === "enviado" ? <p className="mt-3 text-sm font-semibold text-success">Template preparado: {templateName}</p> : null}<form action="/api/certificate-template-uploads" method="post" encType="multipart/form-data" className="mt-5 grid gap-3"><input type="hidden" name="organization_id" value={organization.organization_id} /><FileUploadPreview name="file" accept=".jpg,.jpeg" required label="Imagem do certificado" help="JPG horizontal. Confira o enquadramento antes de enviar." /><Button variant="secondary" size="sm" type="submit" className="w-fit">Preparar template</Button></form></Card>
      <Card><h2 className="text-lg font-semibold text-ink">Configurar certificado</h2><form action={saveGamificationResourceAction} className="mt-5 grid gap-4 sm:grid-cols-2"><input type="hidden" name="resource_type" value="certificate" /><input type="hidden" name="template_file_object_id" value={templateId} /><Label>Certificado existente<Select name="definition_id"><option value="">Criar novo</option>{workspace.certificates.map((item) => <option value={item.definition_id} key={item.definition_id}>{item.name}</option>)}</Select></Label><Label>Nome do certificado<Input name="name" required /></Label><Label>Jornada<Select name="journey_version_id" required><option value="">Selecione</option>{journeyVersions.map((item) => <option value={String(item.id)} key={String(item.id)}>{item.definitionName} · versão {String(item.version_number)}</option>)}</Select></Label><Label>Condição para receber<Select name="requirements_rule_version_id" required><option value="">Selecione</option>{ruleVersions.map((item) => <option value={String(item.id)} key={String(item.id)}>{item.definitionName} · versão {String(item.version_number)}</option>)}</Select></Label><Label>Altura do nome (%)<Input name="name_y_percent" type="number" min="30" max="72" defaultValue="53" /></Label><Label>Altura da jornada (%)<Input name="journey_y_percent" type="number" min="20" max="65" defaultValue="40" /></Label><Label>Cor do texto<Select name="text_color"><option value="primary">Azul Estímulo</option><option value="white">Branco</option></Select></Label><Label>Validade<Select name="validity_mode" defaultValue="never"><option value="never">Não expira</option><option value="months">Expira em meses</option></Select></Label><Label>Meses de validade<Input name="validity_months" type="number" min="1" max="120" defaultValue="12" /></Label><Label>Disponibilidade<Select name="status"><option value="draft">Rascunho</option><option value="published">Publicar agora</option></Select></Label><Button type="submit" className="w-fit sm:col-span-2">Salvar certificado</Button></form></Card>
    </div> : null}
  </div></AppShell>;
}