import { ImageUp } from "lucide-react";
import { AdminDisclosure, AdminSectionNav } from "@/components/admin-section-nav";
import { AppShell } from "@/components/app-shell";
import { CertificateTemplatePositioning } from "@/components/certificate-template-positioning";
import { FileUploadPreview } from "@/components/file-upload-preview";
import { StatusPanel } from "@/components/status-panel";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input, Label, Select, Textarea } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableScroll, Td, Th } from "@/components/ui/table";
import { getAdminProductWorkspace } from "@/lib/admin/product-management";
import { administrativeOrganization } from "@/lib/auth/administrative-access";
import { getAuthContext } from "@/lib/auth/context";
import { saveGamificationResourceAction } from "./actions";

export const dynamic = "force-dynamic";
function single(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] ?? "" : value ?? ""; }
const frequencyLabels: Record<string, string> = { participant: "Uma única vez", enrollment_activity: "Uma vez por aula", enrollment_assessment: "Uma vez por avaliação", path: "Uma vez por trilha", journey: "Uma vez por jornada", participant_day: "Limite diário", participant_week: "Limite semanal", event: "Sem limite" };
const triggerOptions = [
  ["journey.instance.started", "Iniciar uma jornada"],
  ["learning.activity.utility.rated", "Avaliar uma aula"],
  ["learning.activity.completed", "Concluir uma aula"],
  ["assessment.attempt.submitted", "Enviar uma atividade rápida ou avaliação"],
  ["assessment.attempt.passed", "Ser aprovado em uma avaliação"],
  ["learning.practice.evidence.confirmed", "Enviar uma atividade prática"],
  ["journey.path.completed", "Concluir uma trilha"],
] as const;

export default async function AdminGamificationPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = await searchParams;
  const auth = await getAuthContext();
  if (auth.status !== "authenticated") return null;
  const organization = administrativeOrganization(auth.identity);
  if (!organization) return <AppShell area="admin" email={auth.email}><StatusPanel title="Área indisponível" tone="warning">Seu usuário não está vinculado à Estímulo.</StatusPanel></AppShell>;
  const canEdit = organization.permissions.includes("engagement.manage");
  const workspace = await getAdminProductWorkspace(auth.identity.user_account_id, organization.organization_id);
  const ruleVersions = workspace.rules.flatMap((item) => item.versions.map((version) => ({ ...version, definitionName: item.name })));
  const journeyVersions = workspace.journeys.filter((item) => item.status !== "retired").flatMap((item) => item.versions.map((version) => ({ ...version, definitionName: item.name })));
  const type = ["pontos", "selos", "certificados"].includes(single(query.tipo)) ? single(query.tipo) : "pontos";
  const templateId = single(query.template);
  const templateName = single(query.templateNome);
  const activePointRules = workspace.point_rules.filter((item) => item.status !== "retired");

  return <AppShell area="admin" email={auth.email}><div className="grid gap-6">
    <PageHeader eyebrow="Reconhecimento" title="Pontos, selos e certificados" description="Escolha um tipo de reconhecimento e edite apenas seus campos essenciais." />
    {!canEdit ? <StatusPanel title="Somente consulta" tone="info">As configurações estão visíveis, mas não podem ser alteradas.</StatusPanel> : null}
    <AdminSectionNav items={[{ href: "/admin/gamificacao?tipo=pontos", label: "Pontos", active: type === "pontos" }, { href: "/admin/gamificacao?tipo=selos", label: "Selos", active: type === "selos" }, { href: "/admin/gamificacao?tipo=certificados", label: "Certificados", active: type === "certificados" }]} />
    {single(query.sucesso) ? <StatusPanel title="Configuração salva" tone="success">A nova versão foi registrada.</StatusPanel> : null}
    {single(query.erro) ? <StatusPanel title="Não foi possível salvar" tone="warning">Revise os campos obrigatórios e a ação monitorada.</StatusPanel> : null}

    {type === "pontos" ? <div className="grid gap-5">
      <Card><h2 className="text-lg font-semibold text-ink">Regras em uso</h2><p className="mt-1 text-sm text-muted">Mostra qual ação gera pontos, o valor e a frequência.</p>{activePointRules.length ? <TableScroll className="mt-4"><Table><thead><tr><Th>Ação</Th><Th>Pontos</Th><Th>Frequência</Th></tr></thead><tbody>{activePointRules.map((item) => { const version = [...item.versions].sort((a,b) => Number(b.version_number)-Number(a.version_number)).find((entry) => String(entry.status) === "published") ?? item.versions[0]; const recurrence = (version?.recurrence_policy ?? {}) as Record<string, unknown>; return <tr key={item.definition_id}><Td><strong>{item.name}</strong></Td><Td>{String(version?.amount ?? "—")}</Td><Td>{frequencyLabels[String(recurrence.scope ?? "")] ?? "Uma única vez"}</Td></tr>; })}</tbody></Table></TableScroll> : <p className="mt-4 text-sm text-muted">Nenhuma regra criada.</p>}</Card>
      <fieldset disabled={!canEdit} className="contents"><Card><div><h2 className="text-lg font-black text-secondary">Criar ou atualizar regra</h2><p className="mt-1 text-sm text-muted">Escolha a ação e quantos pontos ela vale. Abra as regras avançadas somente quando necessário.</p></div><form action={saveGamificationResourceAction} className="mt-5 grid gap-4"><input type="hidden" name="resource_type" value="point_rule" /><div className="grid gap-4 sm:grid-cols-2"><Label>Regra existente<Select name="definition_id"><option value="">Criar nova</option>{activePointRules.map((item) => <option value={item.definition_id} key={item.definition_id}>{item.name}</option>)}</Select><span className="text-[11px] font-normal text-muted">Selecione para criar uma nova versão da mesma regra.</span></Label><Label>Nome da ação<Input name="name" required placeholder="Ex.: Concluir uma aula" /></Label><Label>Ação que gera pontos<Select name="trigger_event" required><option value="">Selecione</option>{triggerOptions.map(([value,label]) => <option value={value} key={value}>{label}</option>)}</Select></Label><Label>Pontos por ação<Input name="amount" type="number" min="1" required defaultValue="10" /></Label></div><AdminDisclosure title="Limites, condição e publicação" description="Controle repetição, regra de elegibilidade e entrada em vigor."><div className="grid gap-4 sm:grid-cols-2"><Label>Frequência<Select name="frequency" defaultValue="once"><option value="once">Uma única vez</option><option value="per_activity">Uma vez por aula</option><option value="per_assessment">Uma vez por avaliação</option><option value="per_path">Uma vez por trilha</option><option value="per_journey">Uma vez por jornada</option><option value="daily">Limite por dia</option><option value="weekly">Limite por semana</option><option value="unlimited">Sempre que acontecer</option></Select></Label><Label>Máximo no período<Input name="maximum_awards" type="number" min="1" defaultValue="1" /></Label><Label>Condição necessária<Select name="eligibility_rule_version_id" required><option value="">Selecione</option>{ruleVersions.map((item) => <option value={String(item.id)} key={String(item.id)}>{item.definitionName} · versão {String(item.version_number)}</option>)}</Select></Label><Label>Estado<Select name="status"><option value="draft">Salvar rascunho</option><option value="published">Publicar agora</option></Select></Label></div></AdminDisclosure><Button type="submit" className="w-fit">Salvar regra</Button></form></Card></fieldset>
    </div> : null}

    {type === "selos" ? <fieldset disabled={!canEdit} className="contents"><Card><div><h2 className="text-lg font-black text-secondary">Criar ou atualizar selo</h2><p className="mt-1 text-sm text-muted">Defina primeiro o título e o que ele reconhece.</p></div><form action={saveGamificationResourceAction} className="mt-5 grid gap-4"><input type="hidden" name="resource_type" value="badge" /><div className="grid gap-4 sm:grid-cols-2"><Label>Selo existente<Select name="definition_id"><option value="">Criar novo</option>{workspace.badges.map((item) => <option value={item.definition_id} key={item.definition_id}>{item.name}</option>)}</Select></Label><Label>Título para o participante<Input name="title" required /></Label></div><Label>O que o selo reconhece<Textarea name="description" rows={3} required /></Label><AdminDisclosure title="Identificação, condição e publicação" description="Configurações usadas internamente para emitir o selo."><div className="grid gap-4 sm:grid-cols-2"><Label>Nome interno<Input name="name" required /></Label><Label>Condição para receber<Select name="criteria_rule_version_id" required><option value="">Selecione</option>{ruleVersions.map((item) => <option value={String(item.id)} key={String(item.id)}>{item.definitionName} · versão {String(item.version_number)}</option>)}</Select></Label><Label>Estado<Select name="status"><option value="draft">Salvar rascunho</option><option value="published">Publicar agora</option></Select></Label></div></AdminDisclosure><Button type="submit" className="w-fit">Salvar selo</Button></form></Card></fieldset> : null}

    {type === "certificados" ? <div className="grid gap-5"><fieldset disabled={!canEdit} className="contents"><AdminDisclosure title="Preparar imagem do certificado" description="Abra para enviar ou substituir o fundo JPG horizontal."><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary text-white"><ImageUp size={18} /></span><div><p className="text-sm text-muted">A imagem vira o fundo completo do PDF. Deixe espaços livres para nome, jornada e rodapé.</p>{single(query.templateStatus) === "enviado" ? <p className="mt-2 text-sm font-semibold text-success">Template preparado: {templateName}</p> : null}</div></div><form action="/api/certificate-template-uploads" method="post" encType="multipart/form-data" className="mt-5 grid gap-3"><input type="hidden" name="organization_id" value={organization.organization_id} /><FileUploadPreview name="file" accept=".jpg,.jpeg" required label="Imagem do certificado" help="JPG horizontal." /><Button variant="secondary" size="sm" type="submit" className="w-fit">Preparar imagem</Button></form></AdminDisclosure>
      <Card><div><h2 className="text-lg font-black text-secondary">Configurar certificado</h2><p className="mt-1 text-sm text-muted">Escolha o nome e a jornada. Posição, validade e regras ficam nas opções avançadas.</p></div><form action={saveGamificationResourceAction} className="mt-5 grid gap-4"><input type="hidden" name="resource_type" value="certificate" /><input type="hidden" name="template_file_object_id" value={templateId} /><div className="grid gap-4 sm:grid-cols-2"><Label>Certificado existente<Select name="definition_id"><option value="">Criar novo</option>{workspace.certificates.map((item) => <option value={item.definition_id} key={item.definition_id}>{item.name}</option>)}</Select></Label><Label>Nome do certificado<Input name="name" required /></Label><Label>Jornada<Select name="journey_version_id" required><option value="">Selecione</option>{journeyVersions.map((item) => <option value={String(item.id)} key={String(item.id)}>{item.definitionName} · versão {String(item.version_number)}</option>)}</Select></Label></div><AdminDisclosure title="Regra, posicionamento e validade" description="Configurações avançadas do PDF e da emissão."><div className="grid gap-4 sm:grid-cols-2"><Label>Condição para receber<Select name="requirements_rule_version_id" required><option value="">Selecione</option>{ruleVersions.map((item) => <option value={String(item.id)} key={String(item.id)}>{item.definitionName} · versão {String(item.version_number)}</option>)}</Select></Label><Label>Validade<Select name="validity_mode" defaultValue="never"><option value="never">Não expira</option><option value="months">Expira em meses</option></Select></Label><Label>Meses de validade<Input name="validity_months" type="number" min="1" max="120" defaultValue="12" /></Label><Label>Estado<Select name="status"><option value="draft">Salvar rascunho</option><option value="published">Publicar agora</option></Select></Label><div className="sm:col-span-2"><CertificateTemplatePositioning /></div></div></AdminDisclosure><Button type="submit" className="w-fit">Salvar certificado</Button></form></Card></fieldset></div> : null}
  </div></AppShell>;
}
