create or replace function public.get_admin_reporting_dashboard(p_actor_user_account_id uuid,p_organization_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path='pg_catalog'
as $function$
begin
  if not app_private.e14_actor_has_permission(p_actor_user_account_id,p_organization_id,'reporting.read') then
    raise exception 'FORBIDDEN' using errcode='42501';
  end if;
  return jsonb_build_object(
    'organization_id',p_organization_id,
    'generated_at',now(),
    'metrics',jsonb_build_object(
      'participants',(select count(distinct enrollment.entrepreneur_id) from orchestration.enrollments enrollment join core.entrepreneurs entrepreneur on entrepreneur.id=enrollment.entrepreneur_id and entrepreneur.status='active' join catalog.journey_versions version on version.id=enrollment.journey_version_id join catalog.journey_definitions definition on definition.id=version.journey_definition_id where definition.owner_organization_id=p_organization_id and definition.status='active' and definition.code not in ('e14_runtime_validation_journey','task4_verify_journey') and enrollment.status in ('assigned','accepted','active','completed')),
      'enrollments',(select count(*) from orchestration.enrollments enrollment join core.entrepreneurs entrepreneur on entrepreneur.id=enrollment.entrepreneur_id and entrepreneur.status='active' join catalog.journey_versions version on version.id=enrollment.journey_version_id join catalog.journey_definitions definition on definition.id=version.journey_definition_id where definition.owner_organization_id=p_organization_id and definition.status='active' and definition.code not in ('e14_runtime_validation_journey','task4_verify_journey') and enrollment.status in ('assigned','accepted','active','completed')),
      'completed_journeys',(select count(*) from orchestration.journey_instances instance join orchestration.enrollments enrollment on enrollment.id=instance.enrollment_id join core.entrepreneurs entrepreneur on entrepreneur.id=enrollment.entrepreneur_id and entrepreneur.status='active' join catalog.journey_versions version on version.id=enrollment.journey_version_id join catalog.journey_definitions definition on definition.id=version.journey_definition_id where definition.owner_organization_id=p_organization_id and definition.status='active' and definition.code not in ('e14_runtime_validation_journey','task4_verify_journey') and instance.status='completed'),
      'average_progress',(select coalesce(round(avg(progress.completion_ratio*100)::numeric,2),0) from orchestration.progress_projections progress join orchestration.journey_instances instance on instance.id=progress.journey_instance_id join orchestration.enrollments enrollment on enrollment.id=instance.enrollment_id join core.entrepreneurs entrepreneur on entrepreneur.id=enrollment.entrepreneur_id and entrepreneur.status='active' join catalog.journey_versions version on version.id=enrollment.journey_version_id join catalog.journey_definitions definition on definition.id=version.journey_definition_id where definition.owner_organization_id=p_organization_id and definition.status='active' and definition.code not in ('e14_runtime_validation_journey','task4_verify_journey')),
      'points_issued',(select coalesce(sum(ledger.amount),0) from engagement.point_ledger ledger join core.entrepreneurs entrepreneur on entrepreneur.id=ledger.entrepreneur_id and entrepreneur.status='active' join orchestration.journey_instances instance on instance.id=ledger.journey_instance_id join orchestration.enrollments enrollment on enrollment.id=instance.enrollment_id join catalog.journey_versions version on version.id=enrollment.journey_version_id join catalog.journey_definitions definition on definition.id=version.journey_definition_id where definition.owner_organization_id=p_organization_id and definition.status='active' and definition.code not in ('e14_runtime_validation_journey','task4_verify_journey')),
      'comments',(select count(*) from engagement.activity_comments comment join orchestration.journey_instances instance on instance.id=comment.journey_instance_id join orchestration.enrollments enrollment on enrollment.id=instance.enrollment_id join catalog.journey_versions version on version.id=enrollment.journey_version_id join catalog.journey_definitions definition on definition.id=version.journey_definition_id where comment.organization_id=p_organization_id and definition.status='active' and definition.code not in ('e14_runtime_validation_journey','task4_verify_journey')),
      'practice_submissions',(select count(*) from assessment.submissions submission join core.entrepreneurs entrepreneur on entrepreneur.id=submission.entrepreneur_id and entrepreneur.status='active' join orchestration.step_instances step on step.id=submission.step_instance_id join orchestration.path_assignments assignment on assignment.id=step.path_assignment_id join orchestration.journey_instances instance on instance.id=assignment.journey_instance_id join orchestration.enrollments enrollment on enrollment.id=instance.enrollment_id join catalog.journey_versions version on version.id=enrollment.journey_version_id join catalog.journey_definitions definition on definition.id=version.journey_definition_id where definition.owner_organization_id=p_organization_id and definition.status='active' and definition.code not in ('e14_runtime_validation_journey','task4_verify_journey')),
      'average_utility_rating',(select coalesce(round(avg(rating.rating)::numeric,2),0) from engagement.activity_utility_ratings rating join orchestration.journey_instances instance on instance.id=rating.journey_instance_id join orchestration.enrollments enrollment on enrollment.id=instance.enrollment_id join catalog.journey_versions version on version.id=enrollment.journey_version_id join catalog.journey_definitions definition on definition.id=version.journey_definition_id where rating.organization_id=p_organization_id and definition.status='active' and definition.code not in ('e14_runtime_validation_journey','task4_verify_journey')),
      'badges_awarded',(select count(*) from engagement.badge_awards award join core.entrepreneurs entrepreneur on entrepreneur.id=award.entrepreneur_id and entrepreneur.status='active' join engagement.badge_versions badge_version on badge_version.id=award.badge_version_id join engagement.badge_definitions badge_definition on badge_definition.id=badge_version.badge_definition_id where badge_definition.owner_organization_id=p_organization_id and award.revoked_at is null),
      'certificates_issued',(select count(*) from engagement.certificate_issuances issuance join core.entrepreneurs entrepreneur on entrepreneur.id=issuance.entrepreneur_id and entrepreneur.status='active' join engagement.certificate_versions certificate_version on certificate_version.id=issuance.certificate_version_id join engagement.certificate_definitions certificate_definition on certificate_definition.id=certificate_version.certificate_definition_id where certificate_definition.owner_organization_id=p_organization_id and issuance.status='issued')
    ),
    'journeys',(select coalesce(jsonb_agg(jsonb_build_object('journey',definition.name,'version',version.version_number,'enrollments',summary.enrollments,'completed',summary.completed,'average_progress',summary.average_progress) order by definition.name,version.version_number),'[]'::jsonb) from (select enrollment.journey_version_id,count(*) enrollments,count(*) filter(where instance.status='completed') completed,coalesce(round(avg(progress.completion_ratio*100)::numeric,2),0) average_progress from orchestration.enrollments enrollment join core.entrepreneurs entrepreneur on entrepreneur.id=enrollment.entrepreneur_id and entrepreneur.status='active' left join orchestration.journey_instances instance on instance.enrollment_id=enrollment.id left join orchestration.progress_projections progress on progress.journey_instance_id=instance.id where enrollment.status in ('assigned','accepted','active','completed') group by enrollment.journey_version_id) summary join catalog.journey_versions version on version.id=summary.journey_version_id join catalog.journey_definitions definition on definition.id=version.journey_definition_id where definition.owner_organization_id=p_organization_id and definition.status='active' and definition.code not in ('e14_runtime_validation_journey','task4_verify_journey')),
    'recent_events','[]'::jsonb
  );
end;
$function$;